app/src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity=Ad::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan("today", message="Arrival date must be later than today's date!")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan(propertyPath="startDate", message="The departure date must be later than the arrival date!")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * Callback called each time a reservation is created
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function prePersist()
    {
        if (empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }

        if (empty($this->amount)) {
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    // difference between two DateTime objects
    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    public function isBookableDates()
    {
        // impossible dates, compare the dates chosen with the impossible dates
        $notAvailableDays = $this->ad->getNotAvailableDays();
        $bookingDays = $this->getDays();

        $formatDay = function($day) {
            return $day->format('Y-m-d');
        };

        // array that contains strings of my days
        $days = array_map($formatDay, $bookingDays);
        $notAvailable = array_map($formatDay, $notAvailableDays);

        foreach ($days as $day) {
            if (array_search($day, $notAvailable) === true) return false;
        }
        return true;
    }

    /**
     * Allow you to retrieve a table of days that correspond to my reservation
     * return a DateTime object array representing the reservation days
     * @return array
     */
    public function getDays()
    {
        $resultat = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60
        );

        $days = array_map(function ($dayTimestamp) {
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $resultat);

        return $days;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->createAt;
    }

    public function setCreateAt(\DateTimeInterface $createAt): self
    {
        $this->createAt = $createAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

app/src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Table(name="`user`")
 * @UniqueEntity(
 *     fields={"email"},
 *     message="Another user has already registered with this email address, please change it"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="You must enter your first name")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="You must enter your last name")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Please enter a valid email!")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Please provide a valid URL for your avatar!")
     */
    private $avatar;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @Assert\EqualTo(propertyPath="hash", message="You have not correctly confirmed your password!")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, minMessage="Your introduction must be at least 10 characters long")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=50, minMessage="Your description must be at least 50 characters long")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Ad::class, mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initializeSlug()
    {
        if (empty($this->slug))
        {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName.' '.$this->lastName);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getFullName() {
        return "{$this->firstName} {$this->lastName}";
    }

    public function getRoles() {
        $roles = $this->userRoles->map(function($role){
            return $role->getTitle();
        })->toArray();

        $roles[] = 'ROLE_USER';

        return $roles;
    }

    public function getPassword() {
        return $this->hash;
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function getSalt() {}

    public function eraseCredentials() {}

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->removeElement($userRole)) {
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

app/src/Controller/Admin/BookingController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Booking;
use App\Service\Pagination;
use App\Form\AdminBookingType;
use App\Service\PaginationService;
use App\Repository\BookingRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    /**
     * @Route("/admin/bookings/{page<\d+>?1}", name="admin_booking_index")
     */
    public function index(BookingRepository $repo, $page, Pagination $pagination)
    {
        $pagination->setEntityClass(Booking::class)
                    ->setPage($page);
        
        return $this->render('admin/booking/index.html.twig', [
            'pagination' => $pagination
        ]);
    }

    /**
     * Allows you to edit a reservation
     *
     * @Route("/admin/bookings/{id}/edit", name="admin_booking_edit")
     *
     * @return Response
     */
    public function edit(Booking $booking, Request $request)
    {
        $form = $this->createForm(AdminBookingType::class, $booking);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) 
        {
            $booking->setAmount(0);
            $this->em->persist($booking);
            $this->em->flush();

            $this->addFlash(
                'success',
                "The reservation {$booking->getId()} has been modified"
            );

            return $this->redirectToRoute("admin_booking_index");
        }

        return $this->render('admin/booking/edit.html.twig', [
            'form' => $form->createView(),
            'booking' => $booking
        ]);
    }

    /**
     * Allows you to delete a reservation
     *
     * @Route("/admin/bookings/{id}/delete", name="admin_booking_delete")
     *
     * @return Response
     */
    public function delete(Booking $booking)
    {
        $this->em->remove($booking);
        $this->em->flush();

        $this->addFlash(
            'success',
            "The reservation has been deleted"
        );

        return $this->redirectToRoute("admin_booking_index");
    }
}

app/src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * @IsGranted("ROLE_USER")
     * @param Ad $ad
     * @param Request $request
     */
    public function book(Ad $ad, Request $request)
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();

            $booking
                ->setBooker($user)
                ->setAd($ad);

            // if the dates are not available, error message
            if (!$booking->isBookableDates()){
                $this->addFlash(
                    'warning',
                    "The dates you have chosen cannot be reserved: they have already been taken!"
                );
            } else {
                $this->em->persist($booking);
                $this->em->flush();

                return $this->redirectToRoute('booking_show', ['id' => $booking->getId(), 'withAlert' => true]);
            }
        }
        
        return $this->render('booking/book.html.twig', [
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }

    /**
     * Used to display a reservation
     * @Route("/booking/{id}", name="booking_show")
     * @param Booking $booking
     * @param Request $request
     * @return Response
     */
    public function show(Booking $booking, Request $request)
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $comment
                ->setAd($booking->getAd())
                ->setAuthor($this->getUser());

            $this->em->persist($comment);
            $this->em->flush();

            $this->addFlash(
                'success',
                "Your comment has been taken into account"
            );
        }

        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
            'form'=> $form->createView()
        ]);
    }
}

app/templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book the ad: {{ ad.title }}{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css"
          integrity="sha512-mSYUmp1HYZDFaVKK//63EcZq4iFWFjxSL+Z3T/aCt4IO9Cejm03q3NKKYN6pFQzY0SBOr8h+eCIAZHPXcpZaNw=="
          crossorigin="anonymous"/>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Book for the ad: <em>{{ ad.title }}</em></h1>
    <p>You are about to book the property of <strong>{{ ad.author.fullName }}</strong>, tell us everything, we'll take care of the rest!</p>

    {{ form_start(form) }}
        <div class="alert alert-light">
            <h2 class="h4">Start by telling us which dates interest you !</h2>
            <div class="row">
                <div class="col">
                    {{ form_row(form.startDate) }}
                </div>
                <div class="col">
                    {{ form_row(form.endDate) }}
                </div>
            </div>
            <h4 class="mt-2">Amount of stay: <span id="amount">...</span> &dollar;</h4>
            <span id="days">0</span> night(s) à {{ ad.price | number_format(2, ',',' ') }} &dollar; by night

            <h4 class="mt-3">Do you have a comment?</h4>
            {{ form_row(form.comment) }}
        </div>

        <h2>You have finished!</h2>
        <p>Dream vacation? Accommodation for work? No matter, we are with you!</p>

        <button type="submit" class="btn btn-success">I book</button>
    {{ form_end(form) }}
</div>
{% endblock %}

app/templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{{ booking.id }}{% endblock %}

{% block body %}

{% set ad = booking.ad %}
{% set author = ad.author %}

<div class="container">
    <h1 class="my-5">Your reservation {{ booking.id }}</h1>

    {% if app.request.query.get('withAlert') %}
        <div class="alert alert-success">
            <h4 class="alert-heading">well done!</h4>
            <p>Your reservation with 
                <strong>
                    <a href="{{ path("user_show", {'slug': author.slug}) }}">{{ author.fullName }}</a>
                </strong>
                for the announcement
                <strong>
                    <a href="{{ path('ads_show', {'slug':ad.slug}) }}">{{ ad.title }}</a>
                </strong>
                has been taken into account!
            </p>
        </div>
    {% endif %}

    <div class="row">
        <div class="col">
            <div class="alert alert-light">
                <h2>Details</h2>
                <dl class="row">
                    <dt class="col-md-4">Number</dt>
                    <dd class="col-md-8">{{ booking.id }}</dd>
                    <dt class="col-md-4">Arrival date</dt>
                    <dd class="col-md-8">{{ booking.startDate | date('d/m/Y') }}</dd>
                    <dt class="col-md-4">Date of departure</dt>
                    <dd class="col-md-8">{{ booking.endDate | date('d/m/Y') }}</dd>
                    <dt class="col-md-4">Number of nights</dt>
                    <dd class="col-md-8">{{ booking.duration }}</dd>
                    <dt class="col-md-4">Total amount</dt>
                    <dd class="col-md-8">{{ booking.amount | number_format(2, ',',' ') }} &dollar;</dd>
                    <dt class="col-md-4">Remark</dt>
                    <dd class="col-md-8">{{ booking.comment | default('No comment') }}</dd>
                </dl>
                <hr>
                <h2 class="alert-heading">Your host</h2>
                <div class="row mb-3">
                    <div class="col-3">
                        <img src="{{ author.picture }}" class="avatar avatar-medium" alt="Avatar of {{ author.fullName }}">
                    </div>
                    <div class="col">
                        <h4><a href="{{ path('user_show', {'slug' : author.slug}) }}">{{ author.fullName }}</a></h4>
                        <span class="badge badge-primary">{{ author.ads|length }} advertisement</span>
                    </div>
                </div>
                {{ author.description |raw }}

                <a href="{{ path("user_show", {'slug' : author.slug}) }}" class="btn btn-primary">More informations on {{ author.firstName }}</a>
            </div>

            <div class="alert alert-light" id="comment">
                <h2 class="alert-heading">Your opinion matters!</h2>
                {% if date() > date(booking.endDate) %}
                    {% set comment = booking.ad.commentFromAuthor(app.user) %}
                    {% if comment is not null %}
                        <blockquote>
                            {{ comment.content }}
                        </blockquote>
                        <strong>Note: </strong>{% include 'partials/rating.html.twig' with {'rating' : comment.rating} %}
                    {% else %}
                      {{ form_start(form) }}
                          {{ form_widget(form) }}
                          <button type="submit" class="btn btn-success">Confirm!</button>
                      {{ form_end(form) }}
                    {% endif %}
                {% else %}
                    <p>You will not be able to rate this ad until your trip is complete!</p>
                {% endif %}
            </div>
        </div>

        <div class="col">
            <div class="alert alert-light">
                <h2 class="alert-heading">Your accommodation</h2>
                <h4><a href="{{ path('ads_show', {'slug': ad.slug}) }}">{{ ad.title }}</a></h4>
                <img src="{{ ad.coverImage }}" alt="Image de {{ ad.title }}" class="img-fluid">

                {{ ad.content | raw }}

                <a href="{{ path('ads_show', {'slug':ad.slug}) }}" class="btn btn-primary">More information</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}