app/src/Entity/Ad.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use App\Repository\AdRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=AdRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"title"},
 *     message="Another ad already has this title, please change it"
 * )
 */
class Ad
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255, minMessage="The title must be more than 10 characters long!")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min="20", minMessage="The introduction must be more than 20 characters")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min="50", minMessage="The description cannot be less than 50 characters")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="ad", orphanRemoval=true)
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initializeSlug()
    {
        if (empty($this->slug))
        {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

     /**
     * Allows you to obtain a table of days not available for this ad
     * a Datetime object array representing busy days
     * 
     * @return array
     */
    public function getNotAvailableDays()
    {
        $notAvailableDays = [];

        foreach ($this->bookings as $booking) {
            // calculate the days between arrival and departure date
            $resultat = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60
            );

            $days = array_map(function($dayTimestamp) {
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);

            $notAvailableDays = array_merge($notAvailableDays, $days);
        }
        return $notAvailableDays;
    }

    /**
     * Allows you to retrieve an author's comment on an ad
     * 
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach ($this->comments as $comment) {
            if ($comment->getAuthor() === $author) return $comment;
        }
        return null;
    }

    /**
     * Allows you to obtain the overall average of the marks for this ad
     * 
     * @return float
     */
    public function getAvgRatings()
    {
        // calculate the sum of the notations
        $sum = array_reduce($this->comments->toArray(), function($total, $comment){
            return $total + $comment->getRating();
        }, 0);
        
        // division to get the average
        if (count($this->comments) > 0) return $sum / count($this->comments);
        return 0;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

app/src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Table(name="`user`")
 * @UniqueEntity(
 *     fields={"email"},
 *     message="Another user has already registered with this email address, please change it"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="You must enter your first name")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="You must enter your last name")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Please enter a valid email!")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Please provide a valid URL for your avatar!")
     */
    private $avatar;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @Assert\EqualTo(propertyPath="hash", message="You have not correctly confirmed your password!")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, minMessage="Your introduction must be at least 10 characters long")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=50, minMessage="Your description must be at least 50 characters long")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Ad::class, mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initializeSlug()
    {
        if (empty($this->slug))
        {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName.' '.$this->lastName);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getFullName() {
        return "{$this->firstName} {$this->lastName}";
    }

    public function getRoles() {
        $roles = $this->userRoles->map(function($role){
            return $role->getTitle();
        })->toArray();

        $roles[] = 'ROLE_USER';

        return $roles;
    }

    public function getPassword() {
        return $this->hash;
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function getSalt() {}

    public function eraseCredentials() {}

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->removeElement($userRole)) {
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

app/templates/ad/_ad.html.twig
{% set url = path('ads_show', {'slug': ad.slug}) %}

<div class="col-md-4">
    <div class="card bg-light mb3">
        <div class="card-header text-center">
            {{ ad.rooms }} bedrooms, <b>{{ ad.price | number_format(2, ',',' ') }}&dollar; / nights</b> <br>
            {% if ad.comments|length > 0 %}
                {% include 'partials/rating.html.twig' with {'rating' : ad.avgRatings} %}
            {% else %}
                <small>Not rated yet</small>
            {% endif %}
        </div>

        <a href="{{ url }}">
            <img src="{{ ad.coverImage }}" alt="Apartment image" style="height: 200px; width: 100%; display: block">
        </a>

        <div class="card-body">
            <h4 class="card-title">
              <a href="{{ url }}">
                {{ ad.title }}
              </a>
            </h4>
            <p class="card-text">
                 {{ ad.introduction }}
            </p>
            <a href="{{ url }}" class="btn btn-primary">Find out more</a>

            {% if app.user and app.user == ad.author %}
                <a href="{{ path('ads_edit', {'slug' : ad.slug}) }}" class="btn btn-secondary">Edit ad</a>
            {% endif %}
        </div>
    </div>
</div>

app/templates/ad/_collectionImage.html.twig
{% block _ad_images_widget %}
    <p>You can add your images here!</p>

    {{ form_widget(form) }}

    <input type="hidden" id="widgets-counter" value="0">
    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">
            <i class="fas fa-plus"></i>
            Add image
        </button>
    </div>
{% endblock %}

{% block _ad_images_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _ad_images_entry_widget %}
    <div class="form-group" id="block_{{ id }}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{ form_widget(form.url) }}
                        {{ form_errors(form.url) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.caption) }}
                        {{ form_errors(form.caption) }}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" data-action="delete" data-target="#block_{{ id }}" class="btn btn-danger">X</button>
            </div>
        </div>
    </div>
{% endblock %}

{% block collection_widget %}
    {% apply spaceless %}
        {% if prototype is defined %}
            {% set attr = attr|merge({'data-prototype': form_row(prototype)}) %}
            {% set attr = attr|merge({'data-prototype-name': prototype.vars.name}) %}
        {% endif %}
        {% set attr = attr|merge({'data-allow-add': allow_add ? 1 : 0}) %}
        {% set attr = attr|merge({'data-allow-remove': allow_delete ? 1 : 0 }) %}
        {% set attr = attr|merge({'data-name-prefix': full_name}) %}
        {{ block('form_widget') }}
    {% endapply %}
{% endblock collection_widget %}

app/templates/ad/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create an ad{% endblock %}

{% form_theme form 'ad/_collectionImage.html.twig' %}

{% block body %}
<div class="container">
    <h1 class=" h1 mt-5 mb-5">Create a new ad</h1>

    {{ form_start(form) }}
        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h2>General informations</h2>
                    <hr>
                    {{ form_row(form.title) }}
                    {{ form_row(form.slug) }}
                    {{ form_row(form.price) }}
                    {{ form_row(form.rooms) }}
                </div>

                <div class="alert alert-light">
                    <h2>Listing details</h2>
                    <hr>
                    {{ form_row(form.introduction) }}
                    {{ form_row(form.content) }}
                </div>
            </div>

            <div class="col">
                <div class="alert alert-light">
                    <h2>Ad images</h2>
                    {{ form_row(form.coverImage) }}
                    {{ form_row(form.images) }}
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary mt-2">Create a new ad</button>
    {{ form_end(form) }}
</div>
{% endblock %}

{#{% form_theme form 'jquery.collection.html.twig' %}#}

{% block javascripts %}
    {# TODO: Добить плагин для дублирование полей добавления картинок #}
    <script src="{{ asset('build/js/ad.js') }}"></script>
    <script src="{{ asset('js/jquery.collection.js') }}"></script>

    <script type="text/javascript">
        $('.my-selector').collection({
            up: '<a href="#">&#x25B2;</a>',
            down: '<a href="#">&#x25BC;</a>',
            add: '<a href="#">[ + ]</a>',
            remove: '<a href="#">[ - ]</a>',
            duplicate: '<a href="#">[ # ]</a>'
            allow_duplicate: true
        });
    </script>
{% endblock %}

app/templates/ad/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editing an ad{% endblock %}

{% form_theme form 'ad/_collectionImage.html.twig' %}

{% block body %}
    <div class="container">
        <h1 class=" h1 mt-5 mb-5">Edit ad: {{ ad.title }}</h1>

        {{ form_start(form) }}
            {{ form_widget(form) }}
            <button type="submit" class="btn btn-primary mt-2">Save the changes</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('build/js/ad.js') }}"></script>
{% endblock %}

app/templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Advertising{% endblock %}

{% block body %}
<div class="container">
    <h2 class="h1 mt-5 mb-4">Announcements of our hosts</h2>

    <div class="row mt-4">
        {% for ad in ads %}
            {% include('ad/_ad.html.twig') %}
        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ ad.title }}
{% endblock %}

{% block body %}
<div class="my-title" style="background-image: url({{ ad.coverImage }})">
    <div class="container">
        <h1>{{ad.title}}</h1>
        <p>{{ad.introduction}}</p>
        <p class="h2">
            <strong>{{ad.rooms}} rooms {{ad.price | number_format(2, ',',' ') }}&dollar;</strong> per night
        </p>
        <a href="{{ path('booking_create', { 'slug': ad.slug }) }}" class="btn btn-primary">Reserve!</a>

        {% if app.user and app.user == ad.author %}
            <a href="{{ path('ads_edit', {'slug' : ad.slug}) }}" class="btn btn-secondary">Edit ad</a>
            <a href="{{ path('ads_delete', {'slug' : ad.slug}) }}" class="btn btn-danger"
               onclick="return confirm(`Are you sure you want to delete the ad: {{ ad.title }} ?`)">
               Delete ad
            </a>
        {% endif %}
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8 mb-3">
            {{ ad.content| raw }}
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    {% for image in ad.images %}
                        <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}" {% if loop.first %}class="active"{% endif %}></li>
                    {% endfor %}
                </ol>
                <div class="carousel-inner">
                    {% for image in ad.images %}
                        <div class="carousel-item {% if loop.first %}active{% endif %}">
                            <img src="{{ image.url }}" class="d-block w-100" alt="...">
                            <div class="carousel-caption d-none d-md-block">
                                <h5 style="color: white; text-shadow: 3px 3px 3px rgba(0,0,0, 0.5);">{{ ad.title }}</h5>
                                <p style="text-shadow: 3px 3px 3px rgba(0,0,0, 0.5);">{{ image.caption }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <hr>

            {% if ad.comments|length > 0 %}
                <h2 class="mb-3">Comments from travelers: </h2>
                <div class="alert alert-info">
                    <h4 class="alert-heading text-center">
                        <div class="row align-items-center">
                            <div class="col">
                                Overall rating given by travelers
                            </div>
                            <div class="col">
                                {% include 'partials/rating.html.twig' with {'rating' : ad.avgRatings } %}
                                <br>
                                <small>(Calculated on {{ ad.comments|length }} opinion)</small>
                            </div>
                        </div>
                    </h4>
                </div>

                {% for comment in ad.comments %}
                    <div class="bg-light rounded mb-3 py-3 px-3">
                        <strong>{{ comment.author.firstName }}</strong> said :
                        <blockquote>
                            {{ comment.content }}
                        </blockquote>
                        <strong>Rating given: </strong>

                        {% include 'partials/rating.html.twig' with {'rating':comment.rating} %}
                    </div>
                {% endfor %}
            {% else %}
                <h2>This ad has no comments yet...</h2>
            {% endif %}
        </div>

        <div class="col">
            {% set a = ad.author %}
            <div class="row mb-3 align-items-center">
                <div class="col-3">
                    <a href="{{ path('user_show', {'slug': a.slug}) }}">
                        <img src="{{ a.avatar }}" class="avatar avatar-medium" alt="Avatar of {{a.fullName}}">
                    </a>
                </div>
                <div class="col">
                    <a href="{{ path('user_show', {'slug': a.slug}) }}">
                    <h3>{{ a.fullName }}</h3>
                    </a>
                    <span class="badge badge-primary">{{ a.ads | length }} advertisement</span>
                </div>
            </div>
            {{ a.description | raw }}
        </div>
    </div>
</div>
{% endblock %}